package Model;

/**
 * Created by Anders on 17-03-2015.
 */
public enum DefaultView {
    AEROWAY,
        AERODROME, APRON, GATE, HELIPAD, HANGAR, NAVIGATIONAID, RUNWAY, TAXIWAY, TERMINAL, WINDSOCK,
    AMENITY,
        BAR, CAFE, DRINKING_WATER, PUB, RESTAURANT, COLLEGE, KINDERGARTEN, LIBRARY,
        FERRY_TERMINAL, FUEL, PARKING, PARKING_ENTRANCE, PARKING_SPACE, TAXI, BANK,CLINIC,
        CINEMA, FOUNTAIN, THEATRE, POLICE, TOILETS,
    BARRIER,
        HENCE, FENCE, KERB, DITCH, HEDGE,
    BOUNDARY,
        ADMINISTRATIVE, NATIONAL_PARK,
    BUILDING,
        HOTEL, CATHEDRAL, CHAPEL, CHURCH, MOSQUE, TEMPLE, SYNAGOGUE, HOSPITAL, SCHOOL, UNIVERSITY, BRIDGE,
    CRAFT,
    EMERGENCY,
    GEOLOGICAL,
    HIGHWAY,
        MOTORWAY, TRUNK, PRIMARY, SECONDARY, TERTIARY, UNCLASSIFIED, RESIDENTIAL,SERVICE,
        LIVING_STREET, PEDESTRIAN, TRACK, BUS_GUIDEWAY, ROAD,
        CYCLEWAY, BRIDLEWAY, STEPS, PATH, FOOTWAY,
    HISTORIC,
    LANDUSE,
        CEMETERY, CONSTRUCTION, INDUSTRIAL, ORCHARD, RESERVOIR, ALLOTMENTS, BASIN,
        FARMLAND, FARMYARD, FOREST, GRASS, GREENFIELD,
    LEISURE,
        GARDEN, COMMON, PARK, PITCH, PLAYGROUND, WATER_PARK,
    MANMADE,
    NATURAL,
        WOOD, SCRUB, HEATH, GRASSLAND, FELL, SAND, SCREE, WATER, WETLAND, BEACH, COASTLINE,
    PLACE,
    POWER,
    RAILWAY,
        SUBWAY,
    ROUTE,
    SHOP,
    TOURISM,
    WATERWAY,
        RIVERBANK, STREAM, CANAL, RIVER, DAM

}