package Model;

/**
 * Created by Anders on 17-03-2015.
 */
public enum ValueName {
    AEROWAY, //##New key##
        AERODROME, APRON, GATE, HELIPAD, HANGAR, NAVIGATIONAID, RUNWAY, TAXIWAY, TERMINAL, WINDSOCK, //Values

    AMENITY, //##New key##
        BAR, CAFE, DRINKING_WATER, PUB, RESTAURANT, COLLEGE, KINDERGARTEN, LIBRARY, SCHOOL, UNIVERSITY,
        FERRY_TERMINAL, FUEL, PARKING, PARKING_ENTRANCE, PARKING_SPACE, TAXI, BANK,CLINIC,
        CINEMA, FOUNTAIN, THEATRE, POLICE, TOILETS, PHARMACEUTICAL, SCHOOL_AREA,

    BARRIER, //##New key##
        HENCE, FENCE, KERB, DITCH, HEDGE,

    BOUNDARY, //##New key##
        ADMINISTRATIVE, NATIONAL_PARK,

    BOUNDS, //##New key## //

    BUILDING, //##New key##
        HOTEL, CATHEDRAL, CHAPEL, CHURCH, MOSQUE, TEMPLE, SYNAGOGUE, HOSPITAL, BRIDGE,


    CRAFT,//##New key##

    CURRENTSTREET, //##New key##

    EMERGENCY,//##New key##

    GEOLOGICAL,//##New key##

    HIGHWAY,//##New key##
        MOTORWAY, MOTORWAY_LINK, TRUNK, TRUNK_LINK, PRIMARY, PRIMARY_LINK, SECONDARY, SECONDARY_LINK, TERTIARY, TERTIARY_LINK,
        UNCLASSIFIED, RESIDENTIAL,SERVICE, LIVING_STREET, PEDESTRIAN, TRACK, BUS_GUIDEWAY, ROAD,
        CYCLEWAY, BRIDLEWAY, STEPS, PATH, FOOTWAY, FOOTWAY_AREA,

    HISTORIC,//##New key##
        ARCHAEOLOGICAL_SITE,

    LANDUSE, //##New key##
        CEMETERY, CONSTRUCTION, INDUSTRIAL, ORCHARD, RESERVOIR, ALLOTMENTS, BASIN,
        FARMLAND, FARMYARD, FOREST, GRASS, GREENFIELD, BROWNFIELD, MEADOW, RESIDENTIAL_AREA, MILITARY,

    LEISURE,//##New key##
        GARDEN, COMMON, PARK, PITCH, PLAYGROUND, WATER_PARK,

    MANMADE,//##New key##

    NATURAL,//##New key##
        WOOD, SCRUB, HEATH, GRASSLAND, FELL, SAND, SCREE, WATER, WETLAND, BEACH, COASTLINE, MUD,


    POWER,//##New key##
        POWER_AREA,

    RAILWAY,//##New key##
        LIGHT_RAIL, RAIL, TRAM, SUBWAY,

    ROUTE,
        FERRY,//##New key##

    PLACE, //##New key##
        ISLAND, ISLET,

    SHOP,//##New key##

    TOURISM,//##New key##

    WATERWAY,//##New key##
        RIVERBANK, STREAM, CANAL, RIVER, DAM,
    MULTIPOLYGON,

    TRAFFICLIGHT_HIGHWAY, TRAFFICLIGHT_PEDESTRIAN,
    LAST_VALUE_NAME
}