package Model;

/**
 * Created by Anders on 17-03-2015.
 */
public enum ValueName {
    AEROWAY, //##New key##
        AERODROME, APRON, GATE, HELIPAD, HANGAR, NAVIGATIONAID, RUNWAY, TAXIWAY, TERMINAL, WINDSOCK, //Values

    AMENITY, //##New key##
        BAR, CAFE, DRINKING_WATER, PUB, RESTAURANT, COLLEGE, KINDERGARTEN, LIBRARY,
        FERRY_TERMINAL, FUEL, PARKING, PARKING_ENTRANCE, PARKING_SPACE, TAXI, BANK,CLINIC,
        CINEMA, FOUNTAIN, THEATRE, POLICE, TOILETS,

    BARRIER, //##New key##
        HENCE, FENCE, KERB, DITCH, HEDGE,

    BOUNDARY, //##New key##
        ADMINISTRATIVE, NATIONAL_PARK,

    BBOX, //##New key## //TODO: bbox

    BUILDING, //##New key##
        HOTEL, CATHEDRAL, CHAPEL, CHURCH, MOSQUE, TEMPLE, SYNAGOGUE, HOSPITAL, SCHOOL, UNIVERSITY, BRIDGE,

    CRAFT,//##New key##

    EMERGENCY,//##New key##

    GEOLOGICAL,//##New key##

    HIGHWAY,//##New key##
        MOTORWAY, MOTORWAY_LINK, TRUNK, TRUNK_LINK, PRIMARY, PRIMARY_LINK, SECONDARY, SECONDARY_LINK, TERTIARY, TERTIARY_LINK,
        UNCLASSIFIED, RESIDENTIAL,SERVICE, LIVING_STREET, PEDESTRIAN, TRACK, BUS_GUIDEWAY, ROAD,
        CYCLEWAY, BRIDLEWAY, STEPS, PATH, FOOTWAY, FOOTWAY_AREA,

    HISTORIC,//##New key##
        ARCHAEOLOGICAL_SITE,

    LANDUSE, //##New key##
        CEMETERY, CONSTRUCTION, INDUSTRIAL, ORCHARD, RESERVOIR, ALLOTMENTS, BASIN,
        FARMLAND, FARMYARD, FOREST, GRASS, GREENFIELD,

    LEISURE,//##New key##
        GARDEN, COMMON, PARK, PITCH, PLAYGROUND, WATER_PARK,

    MANMADE,//##New key##

    NATURAL,//##New key##
        WOOD, SCRUB, HEATH, GRASSLAND, FELL, SAND, SCREE, WATER, WETLAND, BEACH, COASTLINE,

    PLACE,//##New key##

    POWER,//##New key##

    RAILWAY,//##New key##
        LIGHT_RAIL, RAIL, TRAM, SUBWAY,

    ROUTE,
        FERRY,//##New key##

    SHOP,//##New key##

    TOURISM,//##New key##

    WATERWAY,//##New key##
        RIVERBANK, STREAM, CANAL, RIVER, DAM,
    LAST_VALUE_NAME
}